### ISSUE TITLE
implement author edits in post tools

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#114]
this is old.reddit:

![Screenshot 2023-12-14 at 11 40 17 AM](https://github.com/plebbit/seedit/assets/117766773/a7d98d5c-1193-4e06-a43d-65045f86ab39)

**Comment by plebeius-eth** [comment]
>edit reason would be nice as it could be displayed in a special way in other frontends, other than people just manually adding Edit: blablabla
not sure there's a good looking way to add it to the UI though

**Comment by plebeius-eth** [comment]
5055fde320db05699c4e83066998bd5abdc74252
added edit menu in "edit" button, edit form, asterisk with timestamp title like on old reddit

![Image](https://github.com/plebbit/seedit/assets/117766773/d3ad281d-c18c-447f-bf23-e6e5cc6c533b)
![Image](https://github.com/plebbit/seedit/assets/117766773/9b390600-47a1-4f7f-bf75-996c429da36c)

**Comment by estebanabaroa** [comment]
an edit reason box at the bottom could be good

and maybe the options box to set spoiler? not sure since link cannot be edited

I might just call the buttons "edit" -> edit | delete

edit content seems incorrect since you can also edit flair, reason and spoiler, delete post seems incorrect and redundant
