### ISSUE TITLE
add: info banner on profile page when first accessed

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#372]
https://t.me/seeditreact/6754

**Comment by plebeius-eth** [comment]
6ddb4d7928d57b8e4d8292ba4b7993a33849eb0f
6d3397082a58a96959052031fc5fb1a2fa0de364

**Comment by estebanabaroa** [comment]
imo this would be better

Your account u/ABCQEWR was created. [Set display name] [Back up private key] [Learn more]

the links or buttons could lead to the relevant section in the preferences instead of just a general link to "preferences". and the Learn more blog post could explain that accounts arent synced and how they are automatically generated and stored locally.

**Comment by plebeius-eth** [comment]
done 1a245b5164092df671af57811aa7fdc1ba534848

[Set display name] and [Back up private key] link to the relevant setting, scrolling to it and highlighting it with the same yellow color as permalinked replies. [Learn more] links to the new about page, scrolling to the paragraph explaining how the account is created.
