### ISSUE TITLE
add: sort replies by new, old, and default with top

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#468]
They are already sorted by top, but it says "best". It should say "top", and also allow to sort by new or old. We can add the other sort types later, once they get added to the API.

**Comment by plebeius-eth** [comment]
97c990ef1719f16b5b44f8f810dfef704dfab33b

**Comment by estebanabaroa** [comment]
we already have the code for sort by best if you want to add it https://github.com/plebbit/plebbit-react-hooks/blob/77aa5d00542414af0b13afe1e642960b0848aff5/src/stores/feeds/feed-sorter.ts#L98

we probably wont have top sort in replies because of https://github.com/plebbit/plebbit-js/issues/44#issuecomment-2349558645

the reply sorts will probably only be 

```
best
new
newFlat (telegram style flat conversations, where you see newer first, and scroll to older)
old
oldFlat (4chan style flat replies)
```

**Comment by plebeius-eth** [comment]
changed "top" to "best", using that algo
